repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --show-fixes]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
    - id: basedpyright
      name: basedpyright
      entry: basedpyright
      language: python
      types: [python]
      pass_filenames: false
      additional_dependencies: [basedpyright==1.37.1]
    - id: pip-compile
      name: compile requirements/requirements.txt
      entry: uv
      args: ["pip", "compile", "-o", "requirements/requirements.txt"]
      language: python
      always_run: false
      files: pyproject.toml$
      additional_dependencies: [uv]
    - id: pip-compile-dev
      name: compile requirements/dev.txt
      entry: uv
      args: ["pip", "compile", "--extra", "dev", "-o", "requirements/dev.txt", "-c", "requirements/requirements.txt"]
      language: python
      always_run: false
      files: pyproject.toml$
      additional_dependencies: [uv]
    - id: pip-compile-pandas
      name: compile requirements/pandas.txt
      entry: uv
      args: ["pip", "compile", "--extra", "pandas", "-o", "requirements/pandas.txt", "-c", "requirements/requirements.txt"]
      language: python
      files: pyproject.toml$
      additional_dependencies: [uv]
    - id: pip-compile-polars
      name: compile requirements/polars.txt
      entry: uv
      args: ["pip", "compile", "--extra", "polars", "-o", "requirements/polars.txt", "-c", "requirements/requirements.txt"]
      language: python
      files: pyproject.toml$
      additional_dependencies: [uv]
    - id: pip-compile-docs
      name: compile requirements/docs.txt
      entry: uv
      args: ["pip", "compile", "--extra", "docs", "-o", "requirements/docs.txt", "-c", "requirements/requirements.txt"]
      language: python
      always_run: false
      files: pyproject.toml$
      additional_dependencies: [uv]
    - id: pip-compile-transformers
      name: compile requirements/transformers.txt
      entry: uv
      args: ["pip", "compile", "--extra", "transformers", "-o", "requirements/transformers.txt", "-c", "requirements/requirements.txt"]
      language: python
      always_run: false
      files: pyproject.toml$
      additional_dependencies: [uv]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.6
    hooks:
      - id: uv-lock
      - id: uv-sync
        args: ["--extra", "dev", "--extra", "docs", "--extra", "pandas", "--extra", "polars", "--extra", "transformers"]
