name: Vulnerability scan
on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - "main"
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vulnerability-scan:
    strategy:
      matrix:
        extras:
          - ''
          - dev
          - docs
          - pandas
          - polars
          - transformers
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout hirundo-python-sdk
        uses: actions/checkout@v4
      - name: No-op on pull_request
        if: github.event_name == 'pull_request'
        run: echo "Skipping vulnerability scan on PR; marking job success."
      - if: ${{ matrix.extras != '' && contains(fromJSON('["dev", "docs"]'), matrix.extras) }}
        run: uv pip compile pyproject.toml --group ${{ matrix.extras }}
      - if: ${{ matrix.extras != '' && !contains(fromJSON('["dev", "docs"]'), matrix.extras) }}
        run: uv pip compile pyproject.toml --extra ${{ matrix.extras }}
      - if: ${{ matrix.extras == '' }}
        run: uv pip compile pyproject.toml
      - uses: pypa/gh-action-pip-audit@v1.1.0
        if: github.event_name != 'pull_request'
        with:
          inputs: requirements.txt
